const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("gordonDesktop", {
  bootstrap: () => ipcRenderer.invoke("gordon:bootstrap"),
  listModelSettings: () => ipcRenderer.invoke("gordon:model-settings:list"),
  upsertModelProfile: (profile) => ipcRenderer.invoke("gordon:model-settings:upsert", profile),
  activateModelProfile: (profileId) => ipcRenderer.invoke("gordon:model-settings:activate", profileId),
  toggleModelProfileStatus: (profileId) => ipcRenderer.invoke("gordon:model-settings:toggle-status", profileId),
  deleteModelProfile: (profileId) => ipcRenderer.invoke("gordon:model-settings:delete", profileId),
  invokeModelText: (request) => ipcRenderer.invoke("gordon:model:invoke-text", request),
  queryModelBalance: (request) => ipcRenderer.invoke("gordon:model:query-balance", request),
  listSkillDefinitions: () => ipcRenderer.invoke("gordon:skills:list"),
  upsertSkillDefinition: (skill) => ipcRenderer.invoke("gordon:skills:upsert", skill),
  importSkillDefinitionFromGithub: (request) => ipcRenderer.invoke("gordon:skills:import-from-github", request),
  toggleSkillDefinitionStatus: (skillId) => ipcRenderer.invoke("gordon:skills:toggle-status", skillId),
  deleteSkillDefinition: (skillId) => ipcRenderer.invoke("gordon:skills:delete", skillId),
  listMcpServers: () => ipcRenderer.invoke("gordon:mcp-servers:list"),
  upsertMcpServer: (server) => ipcRenderer.invoke("gordon:mcp-servers:upsert", server),
  toggleMcpServerStatus: (serverId) => ipcRenderer.invoke("gordon:mcp-servers:toggle-status", serverId),
  deleteMcpServer: (serverId) => ipcRenderer.invoke("gordon:mcp-servers:delete", serverId),
  listMcpServerTools: (serverId) => ipcRenderer.invoke("gordon:mcp-servers:list-tools", serverId),
  callMcpServerTool: (request) => ipcRenderer.invoke("gordon:mcp-servers:call-tool", request),
  listAgentProfiles: () => ipcRenderer.invoke("gordon:agent-profiles:list"),
  upsertAgentProfile: (profile) => ipcRenderer.invoke("gordon:agent-profiles:upsert", profile),
  toggleAgentProfileStatus: (profileId) => ipcRenderer.invoke("gordon:agent-profiles:toggle-status", profileId),
  deleteAgentProfile: (profileId) => ipcRenderer.invoke("gordon:agent-profiles:delete", profileId),
  runAgent: (request) => ipcRenderer.invoke("gordon:agent:run", request),
  listCommandWorkshopSessions: () => ipcRenderer.invoke("gordon:command-workshop:list"),
  upsertCommandWorkshopSession: (session) => ipcRenderer.invoke("gordon:command-workshop:upsert", session),
  deleteCommandWorkshopSession: (sessionId) => ipcRenderer.invoke("gordon:command-workshop:delete", sessionId),
  listWeeklyProgress: () => ipcRenderer.invoke("gordon:weekly-progress:list"),
  saveWeeklyProgress: (record) => ipcRenderer.invoke("gordon:weekly-progress:save", record),
  deleteWeeklyProgress: (recordId) => ipcRenderer.invoke("gordon:weekly-progress:delete", recordId),
  rewriteWeeklyProgressItem: (request) => ipcRenderer.invoke("gordon:weekly-progress:rewrite", request),
  generateDailyProgressReport: (request) => ipcRenderer.invoke("gordon:weekly-progress:generate-daily-report", request),
  generateWeeklyProgressReport: (request) => ipcRenderer.invoke("gordon:weekly-progress:generate-report", request)
});
